email ="email@aptiv.com"
email_password = '*****'
JIRA_URL = "https://jiraprod.aptiv.com/"
EXCEL_PATH_READ = r'C:\Users\UserName\Grupo Carso\QTC Engineering - Home office\FolderName\home_office.xlsx'
NAME_COLABORADOR ='name'
email_confirm_receiver ='name@condumex.com.mx'
TOTAL_HOURS='9'
STATUS_TICKET='In Progress'
PROYECTO="Connected services Parsed"
USER_ID="aptiv_userId"